version: '3.4'

services:
  catalogdb:
    image: mongo
  basketdb:
    image: redis
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Servives/Catalog/Catalog.API/Dockerfile
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Servives/Basket/Basket.API/Dockerfile

volumes:
  mongo_data:

